model = "gpt-6-astra"
model_reasoning_effort = "medium"


notify = ["/Users/patrickspieker/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
service_tier = "default"

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/patrickspieker/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/patrickspieker/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[projects."/Users/patrickspieker/code/antaeus/hdw-app"]
trust_level = "trusted"

[projects."/Users/patrickspieker/setup_scripts"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/antaeus/web-app"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/antaeus/api"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-05-23/let-s-connect-figma-here"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-05-23/also-let-s-connect-xcode"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-05-23/okay-xcode-is-connected-via-the"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-05-23/i-m-on-a-mac-and"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-05-23/planning-to-hike-from-paradise-to"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-06-29/find"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/antaeus/utils"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-06-30/i-m"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-01/add"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-03/have"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-05/read"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Westport House"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/which-of-the-big-four-sports"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/l"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/the-user-of-the-apec-abtc"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/d"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/can"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-06/i-wa"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-07/help-me-understand-some-concepts-because"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-07/2-options-2-eufy-e30s-and"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-07/ho"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-07/par"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/you"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/can"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/how"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/clear"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/go"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-23/i-m"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-24/go"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-24/go-look-at-all-the-tickest"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-24/do"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-24/se"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-07-28/garage-eave-lighting-spec-effect-concealed"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/ts-learning"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-08-04/realtime-voice-chat"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-08-17/how-many-breaths-are-in-a"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/to-epub-utils"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/antaeus/healthwallet-app"]
trust_level = "trusted"

[projects."/Users/patrickspieker/code/antaeus/antaeus.health"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-08-28/wr"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-09-01/can"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-09-01/can-2"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-09-01/is"]
trust_level = "trusted"

[projects."/Users/patrickspieker/Documents/Codex/2026-09-01/cr"]
trust_level = "trusted"

[mcp_servers.xcode]
command = "xcrun"
args = ["mcpbridge"]

[mcp_servers.xcode.tools.BuildProject]
approval_mode = "approve"

[mcp_servers.xcode.tools.GetTestList]
approval_mode = "approve"

[mcp_servers.xcode.tools.RunSomeTests]
approval_mode = "approve"

[mcp_servers.xcode.tools.XcodeListWindows]
approval_mode = "approve"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/patrickspieker/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/patrickspieker/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.908.40834"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/patrickspieker/.codex/plugins/cache/openai-bundled/browser/26.908.40834/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/patrickspieker/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.XcodeBuildMCP]
command = "xcodebuildmcp"
args = ["mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--isolated"]

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[desktop]
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
open-link-in-target-preference = "in-app-browser"
keepRemoteControlAwakeWhilePluggedIn = true

[desktop.open-in-target-preferences]
global = "vscode"

[desktop.open-in-target-preferences.perPath]
"/Users/patrickspieker/code/hdw/HDW" = "vscode"
"/Users/patrickspieker/.codex/worktrees/275b/web-app" = "vscode"
"/Users/patrickspieker/.codex/worktrees/2aa3/web-app" = "vscode"
"/Users/patrickspieker/code/antaeus/utils" = "ghostty"
"/Users/patrickspieker/.codex/worktrees/df6c/api" = "vscode"

[features]
js_repl = false

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "9230e2bd8b24b7ac7a0ba6774c64bf0d78ecdabbdd91d0ed627b02a587bae2df"
